"""Run a single translation model attempt."""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import TYPE_CHECKING
from typing import Any

from opentelemetry.trace import SpanKind

from src.config.tracing import tracer_pipeline
from src.config.translation_routing import ModelRoute
from src.worker.doctranslator.doctranslator_exception.DocTranslatorException import (
    InputFileGeneratedByDocTranslatorError,
)
from src.worker.doctranslator.doctranslator_exception.DocTranslatorException import (
    ScannedPDFError,
)
from src.worker.doctranslator.format.pdf.translation_config import (
    SharedContextCrossSplitPart,
)
from src.worker.doctranslator.format.pdf.translation_config import TranslationConfig
from src.worker.services.llm_cost_service import get_vertex_llm_cost_service
from src.worker.services.quality_judge_service import GoogleADKJudgeAgent
from src.worker.services.quality_judge_service import QualityJudgeResult
from src.worker.services.quality_judge_service import extract_attempt_segments
from src.worker.services.token_verification_service import (
    log_token_verification_warning,
)
from src.worker.services.token_verification_service import verify_protected_tokens

if TYPE_CHECKING:
    from src.worker.services.processor_service import JobProcessor

logger = logging.getLogger(__name__)

# Failures caused by the *document's shape*, not the model, are identical
# on every model in the chain -- re-parsing the whole PDF 2-3 more times
# with a different LLM cannot fix "this PDF has no text layer" or "this
# file was already translated". Retrying them wastes a full IL
# parse + per-page pixmap render per wasted attempt
# (implementation_plan.md Phase B.3.1).
NON_RETRYABLE_EXCEPTIONS: tuple[type[Exception], ...] = (
    ScannedPDFError,
    InputFileGeneratedByDocTranslatorError,
)


class TranslationAttemptRunner:
    """Execute one model attempt: translate, judge quality, collect usage."""

    def __init__(self, processor: JobProcessor):
        self._processor = processor
        self._cost_service = get_vertex_llm_cost_service()

    async def run_attempt(
        self,
        *,
        model_index: int,
        model_list: list[ModelRoute] | list[str],
        config: dict[str, Any],
        output_base_dir: Path,
        max_attempts: int,
        judge: GoogleADKJudgeAgent,
        shared_context: SharedContextCrossSplitPart | None = None,
    ) -> tuple[
        dict[str, Any] | None,
        dict[str, Any],
        TranslationConfig | None,
        QualityJudgeResult | None,
        dict[str, Any] | None,
    ]:
        attempt_index = model_index + 1
        selected_route = model_list[model_index]
        if isinstance(selected_route, ModelRoute):
            selected_model = selected_route.model_id
            selected_region = selected_route.region
        else:
            selected_model = str(selected_route)
            selected_region = None
        attempt_output_dir = output_base_dir / f"iter_{attempt_index}"
        attempt_output_dir.mkdir(parents=True, exist_ok=True)
        attempt_config = {
            **config,
            "selected_model": selected_model,
            "selected_model_region": selected_region,
            "attempt_index": attempt_index,
        }
        logger.info(
            f"Attempt {attempt_index}/{max_attempts}: attempt_config={attempt_config}"
        )
        translation_config = self._processor._build_translation_config(
            attempt_config, attempt_output_dir, shared_context=shared_context
        )

        await self._processor.progress_tracker.update(
            self._processor.PROGRESS_START,
            f"Attempt {attempt_index}/{max_attempts}: model={selected_model}",
        )
        try:
            with tracer_pipeline.start_as_current_span(
                "pipeline.translation",
                kind=SpanKind.INTERNAL,
                attributes={
                    "translation.attempt": attempt_index,
                    "translation.model": selected_model,
                },
            ):
                attempt_result = await self._processor._run_single_attempt(
                    translation_config, attempt_config
                )
        except NON_RETRYABLE_EXCEPTIONS:
            # Document-shape failures (scanned/no-text-layer PDF, or a
            # PDF already generated by DocTranslator) are identical on
            # every model in the chain -- re-raise immediately instead of
            # burning the rest of MAX_MODEL_ATTEMPTS re-parsing the same
            # broken document (implementation_plan.md Phase B.3.1).
            logger.warning(
                f"Attempt {attempt_index} failed with a non-retryable "
                f"document error; skipping remaining model attempts.",
                exc_info=True,
            )
            raise
        except Exception as exc:
            logger.exception(
                f"Attempt {attempt_index} failed with model {selected_model} with exception: {exc}"
            )
            if attempt_index == max_attempts:
                raise
            return None, attempt_config, None, None, None

        quality_result: QualityJudgeResult | None = None
        token_verification_dict: dict[str, Any] | None = None
        # Aligned pairs, not two blobs: the judge chunks on pairs so source
        # and target cannot drift apart, and a paragraph translated to
        # nothing is scored as an omission instead of silently shifting
        # every later paragraph against the wrong source.
        segments = extract_attempt_segments(Path(str(translation_config.working_dir)))
        source_text = "\n".join(source for source, _ in segments)
        translated_text = "\n".join(target for _, target in segments if target)
        if judge is not None:
            with tracer_pipeline.start_as_current_span(
                "pipeline.quality_judge",
                kind=SpanKind.INTERNAL,
                attributes={"translation.attempt": attempt_index},
            ):
                quality_result = await self._evaluate_attempt_quality(
                    judge=judge,
                    segments=segments,
                    job_id=str(attempt_config.get("job_id", "")),
                )
        # implementation_plan.md D.6.1 (EC-01/02/14): best-effort,
        # non-blocking check that protected tokens (URLs, emails,
        # currency, CIDR blocks, ticket IDs, CLI flags, bare digit
        # sequences) present in the source still appear verbatim in the
        # translation -- independent of the quality judge, so it also
        # runs when the judge is disabled. Logged as a quality warning
        # and recorded in the attempt report; never fails the attempt.
        token_verification = verify_protected_tokens(source_text, translated_text)
        log_token_verification_warning(
            token_verification,
            job_id=str(attempt_config.get("job_id", "")),
            attempt_index=attempt_index,
        )
        token_verification_dict = token_verification.to_dict()
        token_usage = self.collect_token_usage(
            translation_config, selected_model, selected_region
        )
        attempt_report = {
            "attempt_index": attempt_index,
            "model_id": selected_model,
            "quality": quality_result.to_dict() if quality_result else None,
            "token_usage": token_usage,
            "token_verification": token_verification_dict,
            "working_dir": str(translation_config.working_dir),
            "output_dir": str(attempt_output_dir),
        }
        self._write_quality_report(
            Path(str(translation_config.working_dir)), attempt_report
        )
        return (
            attempt_result,
            attempt_config,
            translation_config,
            quality_result,
            attempt_report,
        )

    async def _evaluate_attempt_quality(
        self,
        *,
        judge: GoogleADKJudgeAgent,
        segments: list[tuple[str, str]],
        job_id: str,
    ) -> QualityJudgeResult:
        if not segments:
            # Previously this returned a hard-coded final_score=0.0. On every
            # split PDF the parent working_dir held no tracking file, so this
            # branch fired on *every* attempt, scored 0.0 (< QUALITY_THRESHOLD),
            # and the loop dutifully re-translated the whole document on every
            # remaining model. "I could not measure this" is not "this is bad".
            return QualityJudgeResult(
                alignment_score=0.0,
                omission_score=0.0,
                hallucination_score=0.0,
                final_score=0.0,
                pass_fail=False,
                reasons=["No translated segments were available to judge."],
                model=judge.model,
                is_fallback=True,
                inconclusive=True,
                coverage_ratio=0.0,
            )
        return await judge.evaluate_segments_async(segments, job_id=job_id)

    def collect_token_usage(
        self,
        translation_config: TranslationConfig,
        selected_model: str,
        selected_region: str | None = None,
    ) -> dict[str, Any]:
        translator = translation_config.translator
        prompt_tokens = self._processor._counter_value(
            getattr(translator, "prompt_token_count", 0)
        )
        completion_tokens = self._processor._counter_value(
            getattr(translator, "completion_token_count", 0)
        )
        total_tokens = self._processor._counter_value(
            getattr(translator, "token_count", 0)
        )
        cache_hit_tokens = self._processor._counter_value(
            getattr(translator, "cache_hit_prompt_token_count", 0)
        )
        breakdown = self._cost_service.calculate_attempt_cost(
            model_id=selected_model,
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            cache_hit_tokens=cache_hit_tokens,
            region=selected_region,
        )
        return {
            "model_id": selected_model,
            "provider": breakdown.provider,
            "total_tokens": total_tokens,
            "prompt_tokens": prompt_tokens,
            "completion_tokens": completion_tokens,
            "cache_hit_prompt_tokens": cache_hit_tokens,
            "estimated_cost_usd": breakdown.total_cost_usd,
            "cost_breakdown": breakdown.to_dict(),
        }

    def _write_quality_report(
        self, working_dir: Path, attempt_report: dict[str, Any]
    ) -> None:
        try:
            quality_path = working_dir / "quality_report.json"
            quality_path.write_text(
                json.dumps(attempt_report, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )
        except Exception:
            logger.exception(f"Failed to write quality report in {working_dir}")
