sonar.projectKey=Translation
sonar.projectName=Translation Project
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.host.url=http://localhost:9000
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=src/doctranslator/**,src/loaders/**,src/api/middleware.py,src/**/__init__.py
sonar.login=squ_4c4f6fe42500a48874a9e31ef04717d3bbea3161