sonar.projectKey=Translation
sonar.projectName=Translation Project
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.host.url=http://localhost:9000
sonar.login=squ_56abbac0ec09110c5945e1eb77a96100da438cdc
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
