"""Repositories module for loaders."""

from loaders.repositories.cache_repository import ensure_cached
from loaders.repositories.cache_repository import get_file_hash
from loaders.repositories.cache_repository import get_file_size
from loaders.repositories.cache_repository import verify_file_integrity
from loaders.repositories.cache_repository import verify_or_delete
from loaders.repositories.metadata_repository import CMAP_METADATA
from loaders.repositories.metadata_repository import EMBEDDING_FONT_METADATA
from loaders.repositories.metadata_repository import clear_metadata_cache
from loaders.repositories.metadata_repository import get_cmap_metadata
from loaders.repositories.metadata_repository import get_cmap_metadata_by_name
from loaders.repositories.metadata_repository import get_font_metadata
from loaders.repositories.metadata_repository import get_font_metadata_by_name
from loaders.repositories.metadata_repository import get_font_names
